package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sentinel</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:800px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.btn-s{border-color:var(--green);color:var(--green)}.btn-s:hover{background:var(--green);color:var(--bg)}.overview{display:flex;gap:1.5rem;margin-bottom:1rem;font-size:.7rem;color:var(--leather)}.overview .stat b{display:block;font-size:1.4rem;color:var(--cream)}.tabs{display:flex;gap:0;margin-bottom:1rem;border-bottom:1px solid var(--bg3)}.tab{padding:.4rem 1rem;cursor:pointer;font-size:.75rem;color:var(--cm);border-bottom:2px solid transparent}.tab:hover{color:var(--cream)}.tab.active{color:var(--rl);border-bottom-color:var(--rl)}.alert-row{display:flex;align-items:center;gap:.5rem;padding:.5rem;border-bottom:1px solid var(--bg3);font-size:.72rem}.sev{font-size:.6rem;padding:.1rem .3rem;border:1px solid;border-radius:2px;font-weight:700;width:55px;text-align:center}.sev-critical{border-color:var(--red);color:var(--red);background:rgba(196,64,64,.1)}.sev-warning{border-color:var(--gold);color:var(--gold)}.sev-info{border-color:var(--cm);color:var(--cm)}.st-firing{color:var(--red)}.st-acked{color:var(--gold)}.st-resolved{color:var(--green)}.alert-msg{flex:1}.alert-src{font-size:.6rem;color:var(--cm)}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:450px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Sentinel</span></h1><button class="btn btn-p" onclick="showNewRule()">+ Rule</button></div>
<div class="main"><div class="overview" id="ov"></div>
<div class="tabs"><div class="tab active" data-tab="alerts" onclick="switchTab('alerts')">Alerts</div><div class="tab" data-tab="rules" onclick="switchTab('rules')">Rules</div></div>
<div id="pane-alerts"><div id="alertList"></div></div><div id="pane-rules" style="display:none"><div id="ruleList"></div></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function timeAgo(d){if(!d)return'';const s=Math.floor((Date.now()-new Date(d))/1e3);if(s<60)return s+'s ago';if(s<3600)return Math.floor(s/60)+'m ago';return Math.floor(s/3600)+'h ago'}
async function init(){const sd=await api('/api/stats');document.getElementById('ov').innerHTML='<div class="stat"><b style="color:'+(sd.firing?'var(--red)':'var(--green)')+'">'+sd.firing+'</b>Firing</div><div class="stat"><b>'+sd.acked+'</b>Acked</div><div class="stat"><b style="color:var(--green)">'+sd.resolved+'</b>Resolved</div><div class="stat"><b>'+sd.rules+'</b>Rules</div>';loadAlerts();loadRules()}
async function loadAlerts(){const d=await api('/api/alerts');const alerts=d.alerts||[];
document.getElementById('alertList').innerHTML=alerts.length?alerts.map(a=>'<div class="alert-row"><span class="sev sev-'+a.severity+'">'+a.severity+'</span><span class="st-'+a.status+'" style="font-weight:700;width:50px">'+a.status+'</span><span class="alert-msg">'+esc(a.message||a.rule_name)+'</span><span class="alert-src">'+esc(a.source)+'</span><span style="color:var(--cm);font-size:.6rem">'+timeAgo(a.fired_at)+'</span>'+
(a.status==='firing'?'<button class="btn btn-s" style="font-size:.55rem;padding:.1rem .3rem" onclick="ack(\''+a.id+'\')">Ack</button><button class="btn btn-p" style="font-size:.55rem;padding:.1rem .3rem" onclick="resolve(\''+a.id+'\')">Resolve</button>':'')+
(a.status==='acked'?'<button class="btn btn-p" style="font-size:.55rem;padding:.1rem .3rem" onclick="resolve(\''+a.id+'\')">Resolve</button>':'')+'</div>').join(''):'<div class="empty">No alerts. All quiet.</div>'}
async function loadRules(){const d=await api('/api/rules');const rules=d.rules||[];
document.getElementById('ruleList').innerHTML=rules.length?rules.map(r=>'<div class="alert-row"><span class="sev sev-'+r.severity+'">'+r.severity+'</span><span style="flex:1;font-weight:600">'+esc(r.name)+'</span><span style="color:var(--cm);font-size:.65rem">'+r.fire_count+' fires</span><span style="cursor:pointer;font-size:.55rem;color:var(--cm)" onclick="delRule(\''+r.id+'\')">del</span></div>').join(''):'<div class="empty">No rules yet.</div>'}
async function ack(id){await api('/api/alerts/'+id+'/ack',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({by:'dashboard'})});init()}
async function resolve(id){await api('/api/alerts/'+id+'/resolve',{method:'POST'});init()}
async function delRule(id){await api('/api/rules/'+id,{method:'DELETE'});init()}
function switchTab(t){document.querySelectorAll('.tab').forEach(el=>el.classList.toggle('active',el.dataset.tab===t));document.getElementById('pane-alerts').style.display=t==='alerts'?'':'none';document.getElementById('pane-rules').style.display=t==='rules'?'':'none'}
function showNewRule(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Alert Rule</h2><label class="fl">Name</label><input type="text" id="nr-name" placeholder="High CPU"><label class="fl">Severity</label><select id="nr-sev"><option>warning</option><option>critical</option><option>info</option></select><label class="fl">Description</label><input type="text" id="nr-desc"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="saveRule()">Create</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function saveRule(){const b={name:document.getElementById('nr-name').value,severity:document.getElementById('nr-sev').value,description:document.getElementById('nr-desc').value};if(!b.name){alert('Required');return};await api('/api/rules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();init()}
function closeModal(){document.getElementById('modal').innerHTML=''}
init();setInterval(init,10000)
</script></body></html>`
