package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Team struct{ID int64 `json:"id"`;Name string `json:"name"`;SlackWebhook string `json:"slack_webhook"`;EmailAlert string `json:"email_alert"`;CreatedAt time.Time `json:"created_at"`}
type Member struct{ID int64 `json:"id"`;TeamID int64 `json:"team_id"`;Name string `json:"name"`;Email string `json:"email"`;Phone string `json:"phone"`;TZ string `json:"timezone"`;CreatedAt time.Time `json:"created_at"`}
type Shift struct{ID int64 `json:"id"`;TeamID int64 `json:"team_id"`;MemberID int64 `json:"member_id"`;MemberName string `json:"member_name,omitempty"`;StartsAt time.Time `json:"starts_at"`;EndsAt time.Time `json:"ends_at"`;Notes string `json:"notes"`;CreatedAt time.Time `json:"created_at"`}
func Open(dataDir string)(*DB,error){if err:=os.MkdirAll(dataDir,0755);err!=nil{return nil,fmt.Errorf("mkdir: %w",err)};dsn:=filepath.Join(dataDir,"sentinel.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);if err:=migrate(db);err!=nil{return nil,fmt.Errorf("migrate: %w",err)};return &DB{db},nil}
func migrate(db *sql.DB)error{_,err:=db.Exec(`CREATE TABLE IF NOT EXISTS teams(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slack_webhook TEXT DEFAULT '',email_alert TEXT DEFAULT '',created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS members(id INTEGER PRIMARY KEY AUTOINCREMENT,team_id INTEGER NOT NULL,name TEXT NOT NULL,email TEXT DEFAULT '',phone TEXT DEFAULT '',timezone TEXT DEFAULT 'UTC',created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS shifts(id INTEGER PRIMARY KEY AUTOINCREMENT,team_id INTEGER NOT NULL,member_id INTEGER NOT NULL,starts_at DATETIME NOT NULL,ends_at DATETIME NOT NULL,notes TEXT DEFAULT '',created_at DATETIME DEFAULT CURRENT_TIMESTAMP);`);return err}
func(db *DB)ListTeams()([]Team,error){rows,err:=db.Query(`SELECT id,name,slack_webhook,email_alert,created_at FROM teams ORDER BY created_at DESC`);if err!=nil{return nil,err};defer rows.Close();var out[]Team;for rows.Next(){var t Team;rows.Scan(&t.ID,&t.Name,&t.SlackWebhook,&t.EmailAlert,&t.CreatedAt);out=append(out,t)};return out,nil}
func(db *DB)CreateTeam(t *Team)error{res,err:=db.Exec(`INSERT INTO teams(name,slack_webhook,email_alert)VALUES(?,?,?)`,t.Name,t.SlackWebhook,t.EmailAlert);if err!=nil{return err};t.ID,_=res.LastInsertId();return nil}
func(db *DB)DeleteTeam(id int64)error{_,err:=db.Exec(`DELETE FROM teams WHERE id=?`,id);return err}
func(db *DB)ListMembers(teamID int64)([]Member,error){rows,err:=db.Query(`SELECT id,team_id,name,email,phone,timezone,created_at FROM members WHERE team_id=? ORDER BY name`,teamID);if err!=nil{return nil,err};defer rows.Close();var out[]Member;for rows.Next(){var m Member;rows.Scan(&m.ID,&m.TeamID,&m.Name,&m.Email,&m.Phone,&m.TZ,&m.CreatedAt);out=append(out,m)};return out,nil}
func(db *DB)CreateMember(m *Member)error{res,err:=db.Exec(`INSERT INTO members(team_id,name,email,phone,timezone)VALUES(?,?,?,?,?)`,m.TeamID,m.Name,m.Email,m.Phone,m.TZ);if err!=nil{return err};m.ID,_=res.LastInsertId();return nil}
func(db *DB)DeleteMember(id int64)error{_,err:=db.Exec(`DELETE FROM members WHERE id=?`,id);return err}
func(db *DB)ListShifts(teamID int64)([]Shift,error){rows,err:=db.Query(`SELECT s.id,s.team_id,s.member_id,COALESCE(m.name,''),s.starts_at,s.ends_at,s.notes,s.created_at FROM shifts s LEFT JOIN members m ON m.id=s.member_id WHERE s.team_id=? ORDER BY s.starts_at DESC LIMIT 50`,teamID);if err!=nil{return nil,err};defer rows.Close();var out[]Shift;for rows.Next(){var s Shift;rows.Scan(&s.ID,&s.TeamID,&s.MemberID,&s.MemberName,&s.StartsAt,&s.EndsAt,&s.Notes,&s.CreatedAt);out=append(out,s)};return out,nil}
func(db *DB)CreateShift(s *Shift)error{res,err:=db.Exec(`INSERT INTO shifts(team_id,member_id,starts_at,ends_at,notes)VALUES(?,?,?,?,?)`,s.TeamID,s.MemberID,s.StartsAt,s.EndsAt,s.Notes);if err!=nil{return err};s.ID,_=res.LastInsertId();return nil}
func(db *DB)CurrentOnCall(teamID int64)(*Shift,error){now:=time.Now().UTC().Format("2006-01-02 15:04:05");s:=&Shift{};err:=db.QueryRow(`SELECT s.id,s.team_id,s.member_id,COALESCE(m.name,''),s.starts_at,s.ends_at,s.notes,s.created_at FROM shifts s LEFT JOIN members m ON m.id=s.member_id WHERE s.team_id=? AND s.starts_at<=? AND s.ends_at>=? LIMIT 1`,teamID,now,now).Scan(&s.ID,&s.TeamID,&s.MemberID,&s.MemberName,&s.StartsAt,&s.EndsAt,&s.Notes,&s.CreatedAt);if err==sql.ErrNoRows{return nil,nil};return s,err}
func(db *DB)CountTeams()(int,error){var n int;db.QueryRow(`SELECT COUNT(*) FROM teams`).Scan(&n);return n,nil}
func(db *DB)CountShifts()(int,error){var n int;db.QueryRow(`SELECT COUNT(*) FROM shifts`).Scan(&n);return n,nil}
